export default class UrlConstants {
  /**
   * host
   */
  static readonly SERVER = 'https://devapi.qweather.com'
  /**
   * 实时天气
   */
  static readonly WEATHER_NOW = '/v7/weather/now'
  /**
   * 7天天气
   */
  static readonly WEATHER_7D = '/v7/weather/7d'
  /**
   * 24小时天气
   */
  static readonly WEATHER_24H = '/v7/weather/24h'
  /**
   * key
   */
  static readonly PRIVATE_KEY = '852391803c4944869c8ae79d0b748d6d'
}